version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:7.14.0
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  redis:
    image: redis:6.2.5
    restart: always
    ports:
      - 6379:6379
